name: 'Hillbilly '
favicon: null
layout_spectrum: 0.760019252076745
typography_spectrum: 0.22221740102395415
title: 'Hillbilly '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7229291233234107
  lightness: 0.23029675125144422
  saturation: 0.2490671395789832
  rhythmicContrast: 0.5061771292239428
purpose: []
