name: No Somos Inmortales
favicon: null
layout_spectrum: 0.75049
typography_spectrum: 0.50793
title: No Somos Inmortales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d34432'
    - '#dcb186'
    - '#1a181d'
    - '#4b6e72'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5061771292239428
purpose: []
